// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: graphql-editor/subscriptions_service/service.proto

package subscription_service

import (
	context "context"
	messages "github.com/graphql-editor/graphql_editor_messages/go/graphql-editor/messages"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SubscriptionServiceClient is the client API for SubscriptionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SubscriptionServiceClient interface {
	Subscription(ctx context.Context, in *messages.SubscriptionRequest, opts ...grpc.CallOption) (SubscriptionService_SubscriptionClient, error)
}

type subscriptionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSubscriptionServiceClient(cc grpc.ClientConnInterface) SubscriptionServiceClient {
	return &subscriptionServiceClient{cc}
}

func (c *subscriptionServiceClient) Subscription(ctx context.Context, in *messages.SubscriptionRequest, opts ...grpc.CallOption) (SubscriptionService_SubscriptionClient, error) {
	stream, err := c.cc.NewStream(ctx, &SubscriptionService_ServiceDesc.Streams[0], "/graphqleditor.subscription_service.SubscriptionService/Subscription", opts...)
	if err != nil {
		return nil, err
	}
	x := &subscriptionServiceSubscriptionClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SubscriptionService_SubscriptionClient interface {
	Recv() (*messages.SubscriptionResponse, error)
	grpc.ClientStream
}

type subscriptionServiceSubscriptionClient struct {
	grpc.ClientStream
}

func (x *subscriptionServiceSubscriptionClient) Recv() (*messages.SubscriptionResponse, error) {
	m := new(messages.SubscriptionResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SubscriptionServiceServer is the server API for SubscriptionService service.
// All implementations must embed UnimplementedSubscriptionServiceServer
// for forward compatibility
type SubscriptionServiceServer interface {
	Subscription(*messages.SubscriptionRequest, SubscriptionService_SubscriptionServer) error
	mustEmbedUnimplementedSubscriptionServiceServer()
}

// UnimplementedSubscriptionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSubscriptionServiceServer struct {
}

func (UnimplementedSubscriptionServiceServer) Subscription(*messages.SubscriptionRequest, SubscriptionService_SubscriptionServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscription not implemented")
}
func (UnimplementedSubscriptionServiceServer) mustEmbedUnimplementedSubscriptionServiceServer() {}

// UnsafeSubscriptionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubscriptionServiceServer will
// result in compilation errors.
type UnsafeSubscriptionServiceServer interface {
	mustEmbedUnimplementedSubscriptionServiceServer()
}

func RegisterSubscriptionServiceServer(s grpc.ServiceRegistrar, srv SubscriptionServiceServer) {
	s.RegisterService(&SubscriptionService_ServiceDesc, srv)
}

func _SubscriptionService_Subscription_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(messages.SubscriptionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SubscriptionServiceServer).Subscription(m, &subscriptionServiceSubscriptionServer{stream})
}

type SubscriptionService_SubscriptionServer interface {
	Send(*messages.SubscriptionResponse) error
	grpc.ServerStream
}

type subscriptionServiceSubscriptionServer struct {
	grpc.ServerStream
}

func (x *subscriptionServiceSubscriptionServer) Send(m *messages.SubscriptionResponse) error {
	return x.ServerStream.SendMsg(m)
}

// SubscriptionService_ServiceDesc is the grpc.ServiceDesc for SubscriptionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SubscriptionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "graphqleditor.subscription_service.SubscriptionService",
	HandlerType: (*SubscriptionServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscription",
			Handler:       _SubscriptionService_Subscription_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "graphql-editor/subscriptions_service/service.proto",
}
