// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: graphql-editor/messages/messages.proto

package messages

import (
	messages "github.com/graphql-editor/stucco_proto/go/messages"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Runtime int32

const (
	Runtime_NODEJS14 Runtime = 0
)

// Enum value maps for Runtime.
var (
	Runtime_name = map[int32]string{
		0: "NODEJS14",
	}
	Runtime_value = map[string]int32{
		"NODEJS14": 0,
	}
)

func (x Runtime) Enum() *Runtime {
	p := new(Runtime)
	*p = x
	return p
}

func (x Runtime) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Runtime) Descriptor() protoreflect.EnumDescriptor {
	return file_graphql_editor_messages_messages_proto_enumTypes[0].Descriptor()
}

func (Runtime) Type() protoreflect.EnumType {
	return &file_graphql_editor_messages_messages_proto_enumTypes[0]
}

func (x Runtime) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Runtime.Descriptor instead.
func (Runtime) EnumDescriptor() ([]byte, []int) {
	return file_graphql_editor_messages_messages_proto_rawDescGZIP(), []int{0}
}

type Status int32

const (
	Status_OK    Status = 0
	Status_ERROR Status = 1
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "OK",
		1: "ERROR",
	}
	Status_value = map[string]int32{
		"OK":    0,
		"ERROR": 1,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_graphql_editor_messages_messages_proto_enumTypes[1].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_graphql_editor_messages_messages_proto_enumTypes[1]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_graphql_editor_messages_messages_proto_rawDescGZIP(), []int{1}
}

type ReadFunctionStatus int32

const (
	ReadFunctionStatus_READY        ReadFunctionStatus = 0
	ReadFunctionStatus_IN_PROGRESS  ReadFunctionStatus = 1
	ReadFunctionStatus_NOT_DEPLOYED ReadFunctionStatus = 2
)

// Enum value maps for ReadFunctionStatus.
var (
	ReadFunctionStatus_name = map[int32]string{
		0: "READY",
		1: "IN_PROGRESS",
		2: "NOT_DEPLOYED",
	}
	ReadFunctionStatus_value = map[string]int32{
		"READY":        0,
		"IN_PROGRESS":  1,
		"NOT_DEPLOYED": 2,
	}
)

func (x ReadFunctionStatus) Enum() *ReadFunctionStatus {
	p := new(ReadFunctionStatus)
	*p = x
	return p
}

func (x ReadFunctionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReadFunctionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_graphql_editor_messages_messages_proto_enumTypes[2].Descriptor()
}

func (ReadFunctionStatus) Type() protoreflect.EnumType {
	return &file_graphql_editor_messages_messages_proto_enumTypes[2]
}

func (x ReadFunctionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReadFunctionStatus.Descriptor instead.
func (ReadFunctionStatus) EnumDescriptor() ([]byte, []int) {
	return file_graphql_editor_messages_messages_proto_rawDescGZIP(), []int{2}
}

type CreateFunctionResponse_Error_ErrorKind int32

const (
	CreateFunctionResponse_Error_UNKNOWN CreateFunctionResponse_Error_ErrorKind = 0
)

// Enum value maps for CreateFunctionResponse_Error_ErrorKind.
var (
	CreateFunctionResponse_Error_ErrorKind_name = map[int32]string{
		0: "UNKNOWN",
	}
	CreateFunctionResponse_Error_ErrorKind_value = map[string]int32{
		"UNKNOWN": 0,
	}
)

func (x CreateFunctionResponse_Error_ErrorKind) Enum() *CreateFunctionResponse_Error_ErrorKind {
	p := new(CreateFunctionResponse_Error_ErrorKind)
	*p = x
	return p
}

func (x CreateFunctionResponse_Error_ErrorKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateFunctionResponse_Error_ErrorKind) Descriptor() protoreflect.EnumDescriptor {
	return file_graphql_editor_messages_messages_proto_enumTypes[3].Descriptor()
}

func (CreateFunctionResponse_Error_ErrorKind) Type() protoreflect.EnumType {
	return &file_graphql_editor_messages_messages_proto_enumTypes[3]
}

func (x CreateFunctionResponse_Error_ErrorKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateFunctionResponse_Error_ErrorKind.Descriptor instead.
func (CreateFunctionResponse_Error_ErrorKind) EnumDescriptor() ([]byte, []int) {
	return file_graphql_editor_messages_messages_proto_rawDescGZIP(), []int{2, 0, 0}
}

type UpdateFunctionResponse_Error_ErrorKind int32

const (
	UpdateFunctionResponse_Error_UNKNOWN UpdateFunctionResponse_Error_ErrorKind = 0
)

// Enum value maps for UpdateFunctionResponse_Error_ErrorKind.
var (
	UpdateFunctionResponse_Error_ErrorKind_name = map[int32]string{
		0: "UNKNOWN",
	}
	UpdateFunctionResponse_Error_ErrorKind_value = map[string]int32{
		"UNKNOWN": 0,
	}
)

func (x UpdateFunctionResponse_Error_ErrorKind) Enum() *UpdateFunctionResponse_Error_ErrorKind {
	p := new(UpdateFunctionResponse_Error_ErrorKind)
	*p = x
	return p
}

func (x UpdateFunctionResponse_Error_ErrorKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateFunctionResponse_Error_ErrorKind) Descriptor() protoreflect.EnumDescriptor {
	return file_graphql_editor_messages_messages_proto_enumTypes[4].Descriptor()
}

func (UpdateFunctionResponse_Error_ErrorKind) Type() protoreflect.EnumType {
	return &file_graphql_editor_messages_messages_proto_enumTypes[4]
}

func (x UpdateFunctionResponse_Error_ErrorKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateFunctionResponse_Error_ErrorKind.Descriptor instead.
func (UpdateFunctionResponse_Error_ErrorKind) EnumDescriptor() ([]byte, []int) {
	return file_graphql_editor_messages_messages_proto_rawDescGZIP(), []int{6, 0, 0}
}

type DeleteFunctionResponse_Error_ErrorKind int32

const (
	DeleteFunctionResponse_Error_UNKNOWN DeleteFunctionResponse_Error_ErrorKind = 0
)

// Enum value maps for DeleteFunctionResponse_Error_ErrorKind.
var (
	DeleteFunctionResponse_Error_ErrorKind_name = map[int32]string{
		0: "UNKNOWN",
	}
	DeleteFunctionResponse_Error_ErrorKind_value = map[string]int32{
		"UNKNOWN": 0,
	}
)

func (x DeleteFunctionResponse_Error_ErrorKind) Enum() *DeleteFunctionResponse_Error_ErrorKind {
	p := new(DeleteFunctionResponse_Error_ErrorKind)
	*p = x
	return p
}

func (x DeleteFunctionResponse_Error_ErrorKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeleteFunctionResponse_Error_ErrorKind) Descriptor() protoreflect.EnumDescriptor {
	return file_graphql_editor_messages_messages_proto_enumTypes[5].Descriptor()
}

func (DeleteFunctionResponse_Error_ErrorKind) Type() protoreflect.EnumType {
	return &file_graphql_editor_messages_messages_proto_enumTypes[5]
}

func (x DeleteFunctionResponse_Error_ErrorKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeleteFunctionResponse_Error_ErrorKind.Descriptor instead.
func (DeleteFunctionResponse_Error_ErrorKind) EnumDescriptor() ([]byte, []int) {
	return file_graphql_editor_messages_messages_proto_rawDescGZIP(), []int{8, 0, 0}
}

type LogStreamResponse_Error_ErrorKind int32

const (
	LogStreamResponse_Error_UNKNOWN LogStreamResponse_Error_ErrorKind = 0
)

// Enum value maps for LogStreamResponse_Error_ErrorKind.
var (
	LogStreamResponse_Error_ErrorKind_name = map[int32]string{
		0: "UNKNOWN",
	}
	LogStreamResponse_Error_ErrorKind_value = map[string]int32{
		"UNKNOWN": 0,
	}
)

func (x LogStreamResponse_Error_ErrorKind) Enum() *LogStreamResponse_Error_ErrorKind {
	p := new(LogStreamResponse_Error_ErrorKind)
	*p = x
	return p
}

func (x LogStreamResponse_Error_ErrorKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogStreamResponse_Error_ErrorKind) Descriptor() protoreflect.EnumDescriptor {
	return file_graphql_editor_messages_messages_proto_enumTypes[6].Descriptor()
}

func (LogStreamResponse_Error_ErrorKind) Type() protoreflect.EnumType {
	return &file_graphql_editor_messages_messages_proto_enumTypes[6]
}

func (x LogStreamResponse_Error_ErrorKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogStreamResponse_Error_ErrorKind.Descriptor instead.
func (LogStreamResponse_Error_ErrorKind) EnumDescriptor() ([]byte, []int) {
	return file_graphql_editor_messages_messages_proto_rawDescGZIP(), []int{10, 0, 0}
}

type TextStreamResponse_Error_ErrorKind int32

const (
	TextStreamResponse_Error_UNKNOWN TextStreamResponse_Error_ErrorKind = 0
)

// Enum value maps for TextStreamResponse_Error_ErrorKind.
var (
	TextStreamResponse_Error_ErrorKind_name = map[int32]string{
		0: "UNKNOWN",
	}
	TextStreamResponse_Error_ErrorKind_value = map[string]int32{
		"UNKNOWN": 0,
	}
)

func (x TextStreamResponse_Error_ErrorKind) Enum() *TextStreamResponse_Error_ErrorKind {
	p := new(TextStreamResponse_Error_ErrorKind)
	*p = x
	return p
}

func (x TextStreamResponse_Error_ErrorKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TextStreamResponse_Error_ErrorKind) Descriptor() protoreflect.EnumDescriptor {
	return file_graphql_editor_messages_messages_proto_enumTypes[7].Descriptor()
}

func (TextStreamResponse_Error_ErrorKind) Type() protoreflect.EnumType {
	return &file_graphql_editor_messages_messages_proto_enumTypes[7]
}

func (x TextStreamResponse_Error_ErrorKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TextStreamResponse_Error_ErrorKind.Descriptor instead.
func (TextStreamResponse_Error_ErrorKind) EnumDescriptor() ([]byte, []int) {
	return file_graphql_editor_messages_messages_proto_rawDescGZIP(), []int{12, 0, 0}
}

type SubscriptionResponse_Error_ErrorKind int32

const (
	SubscriptionResponse_Error_UNKNOWN SubscriptionResponse_Error_ErrorKind = 0
)

// Enum value maps for SubscriptionResponse_Error_ErrorKind.
var (
	SubscriptionResponse_Error_ErrorKind_name = map[int32]string{
		0: "UNKNOWN",
	}
	SubscriptionResponse_Error_ErrorKind_value = map[string]int32{
		"UNKNOWN": 0,
	}
)

func (x SubscriptionResponse_Error_ErrorKind) Enum() *SubscriptionResponse_Error_ErrorKind {
	p := new(SubscriptionResponse_Error_ErrorKind)
	*p = x
	return p
}

func (x SubscriptionResponse_Error_ErrorKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubscriptionResponse_Error_ErrorKind) Descriptor() protoreflect.EnumDescriptor {
	return file_graphql_editor_messages_messages_proto_enumTypes[8].Descriptor()
}

func (SubscriptionResponse_Error_ErrorKind) Type() protoreflect.EnumType {
	return &file_graphql_editor_messages_messages_proto_enumTypes[8]
}

func (x SubscriptionResponse_Error_ErrorKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubscriptionResponse_Error_ErrorKind.Descriptor instead.
func (SubscriptionResponse_Error_ErrorKind) EnumDescriptor() ([]byte, []int) {
	return file_graphql_editor_messages_messages_proto_rawDescGZIP(), []int{15, 0, 0}
}

type Function struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Project   string   `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	Namespace string   `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	WorkDir   string   `protobuf:"bytes,4,opt,name=work_dir,json=workDir,proto3" json:"work_dir,omitempty"`
	Files     []string `protobuf:"bytes,5,rep,name=files,proto3" json:"files,omitempty"`
	BuildCmd  []string `protobuf:"bytes,6,rep,name=build_cmd,json=buildCmd,proto3" json:"build_cmd,omitempty"`
}

func (x *Function) Reset() {
	*x = Function{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphql_editor_messages_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Function) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Function) ProtoMessage() {}

func (x *Function) ProtoReflect() protoreflect.Message {
	mi := &file_graphql_editor_messages_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Function.ProtoReflect.Descriptor instead.
func (*Function) Descriptor() ([]byte, []int) {
	return file_graphql_editor_messages_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Function) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Function) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *Function) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Function) GetWorkDir() string {
	if x != nil {
		return x.WorkDir
	}
	return ""
}

func (x *Function) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *Function) GetBuildCmd() []string {
	if x != nil {
		return x.BuildCmd
	}
	return nil
}

type CreateFunctionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Function *Function `protobuf:"bytes,1,opt,name=function,proto3" json:"function,omitempty"`
}

func (x *CreateFunctionRequest) Reset() {
	*x = CreateFunctionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphql_editor_messages_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFunctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFunctionRequest) ProtoMessage() {}

func (x *CreateFunctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graphql_editor_messages_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFunctionRequest.ProtoReflect.Descriptor instead.
func (*CreateFunctionRequest) Descriptor() ([]byte, []int) {
	return file_graphql_editor_messages_messages_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFunctionRequest) GetFunction() *Function {
	if x != nil {
		return x.Function
	}
	return nil
}

type CreateFunctionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrackId string                          `protobuf:"bytes,1,opt,name=trackId,proto3" json:"trackId,omitempty"`
	Status  Status                          `protobuf:"varint,2,opt,name=status,proto3,enum=graphqleditor.messages.Status" json:"status,omitempty"`
	Errors  []*CreateFunctionResponse_Error `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
}

func (x *CreateFunctionResponse) Reset() {
	*x = CreateFunctionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphql_editor_messages_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFunctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFunctionResponse) ProtoMessage() {}

func (x *CreateFunctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graphql_editor_messages_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFunctionResponse.ProtoReflect.Descriptor instead.
func (*CreateFunctionResponse) Descriptor() ([]byte, []int) {
	return file_graphql_editor_messages_messages_proto_rawDescGZIP(), []int{2}
}

func (x *CreateFunctionResponse) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

func (x *CreateFunctionResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OK
}

func (x *CreateFunctionResponse) GetErrors() []*CreateFunctionResponse_Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

type ReadFunctionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Function *Function `protobuf:"bytes,1,opt,name=function,proto3" json:"function,omitempty"`
}

func (x *ReadFunctionRequest) Reset() {
	*x = ReadFunctionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphql_editor_messages_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadFunctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFunctionRequest) ProtoMessage() {}

func (x *ReadFunctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graphql_editor_messages_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFunctionRequest.ProtoReflect.Descriptor instead.
func (*ReadFunctionRequest) Descriptor() ([]byte, []int) {
	return file_graphql_editor_messages_messages_proto_rawDescGZIP(), []int{3}
}

func (x *ReadFunctionRequest) GetFunction() *Function {
	if x != nil {
		return x.Function
	}
	return nil
}

type ReadFunctionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status ReadFunctionStatus `protobuf:"varint,1,opt,name=status,proto3,enum=graphqleditor.messages.ReadFunctionStatus" json:"status,omitempty"`
	Url    string             `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *ReadFunctionResponse) Reset() {
	*x = ReadFunctionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphql_editor_messages_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadFunctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFunctionResponse) ProtoMessage() {}

func (x *ReadFunctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graphql_editor_messages_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFunctionResponse.ProtoReflect.Descriptor instead.
func (*ReadFunctionResponse) Descriptor() ([]byte, []int) {
	return file_graphql_editor_messages_messages_proto_rawDescGZIP(), []int{4}
}

func (x *ReadFunctionResponse) GetStatus() ReadFunctionStatus {
	if x != nil {
		return x.Status
	}
	return ReadFunctionStatus_READY
}

func (x *ReadFunctionResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type UpdateFunctionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Function *Function `protobuf:"bytes,1,opt,name=function,proto3" json:"function,omitempty"`
}

func (x *UpdateFunctionRequest) Reset() {
	*x = UpdateFunctionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphql_editor_messages_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFunctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFunctionRequest) ProtoMessage() {}

func (x *UpdateFunctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graphql_editor_messages_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFunctionRequest.ProtoReflect.Descriptor instead.
func (*UpdateFunctionRequest) Descriptor() ([]byte, []int) {
	return file_graphql_editor_messages_messages_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateFunctionRequest) GetFunction() *Function {
	if x != nil {
		return x.Function
	}
	return nil
}

type UpdateFunctionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrackId string                          `protobuf:"bytes,1,opt,name=trackId,proto3" json:"trackId,omitempty"`
	Status  Status                          `protobuf:"varint,2,opt,name=status,proto3,enum=graphqleditor.messages.Status" json:"status,omitempty"`
	Errors  []*UpdateFunctionResponse_Error `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
}

func (x *UpdateFunctionResponse) Reset() {
	*x = UpdateFunctionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphql_editor_messages_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFunctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFunctionResponse) ProtoMessage() {}

func (x *UpdateFunctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graphql_editor_messages_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFunctionResponse.ProtoReflect.Descriptor instead.
func (*UpdateFunctionResponse) Descriptor() ([]byte, []int) {
	return file_graphql_editor_messages_messages_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateFunctionResponse) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

func (x *UpdateFunctionResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OK
}

func (x *UpdateFunctionResponse) GetErrors() []*UpdateFunctionResponse_Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

type DeleteFunctionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Function *Function `protobuf:"bytes,1,opt,name=function,proto3" json:"function,omitempty"`
}

func (x *DeleteFunctionRequest) Reset() {
	*x = DeleteFunctionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphql_editor_messages_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFunctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFunctionRequest) ProtoMessage() {}

func (x *DeleteFunctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graphql_editor_messages_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFunctionRequest.ProtoReflect.Descriptor instead.
func (*DeleteFunctionRequest) Descriptor() ([]byte, []int) {
	return file_graphql_editor_messages_messages_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteFunctionRequest) GetFunction() *Function {
	if x != nil {
		return x.Function
	}
	return nil
}

type DeleteFunctionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrackId string                          `protobuf:"bytes,1,opt,name=trackId,proto3" json:"trackId,omitempty"`
	Status  Status                          `protobuf:"varint,2,opt,name=status,proto3,enum=graphqleditor.messages.Status" json:"status,omitempty"`
	Errors  []*DeleteFunctionResponse_Error `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
}

func (x *DeleteFunctionResponse) Reset() {
	*x = DeleteFunctionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphql_editor_messages_messages_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFunctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFunctionResponse) ProtoMessage() {}

func (x *DeleteFunctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graphql_editor_messages_messages_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFunctionResponse.ProtoReflect.Descriptor instead.
func (*DeleteFunctionResponse) Descriptor() ([]byte, []int) {
	return file_graphql_editor_messages_messages_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteFunctionResponse) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

func (x *DeleteFunctionResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OK
}

func (x *DeleteFunctionResponse) GetErrors() []*DeleteFunctionResponse_Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

type LogStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Function *Function `protobuf:"bytes,1,opt,name=function,proto3" json:"function,omitempty"`
}

func (x *LogStreamRequest) Reset() {
	*x = LogStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphql_editor_messages_messages_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogStreamRequest) ProtoMessage() {}

func (x *LogStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graphql_editor_messages_messages_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogStreamRequest.ProtoReflect.Descriptor instead.
func (*LogStreamRequest) Descriptor() ([]byte, []int) {
	return file_graphql_editor_messages_messages_proto_rawDescGZIP(), []int{9}
}

func (x *LogStreamRequest) GetFunction() *Function {
	if x != nil {
		return x.Function
	}
	return nil
}

type LogStreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrackId string                     `protobuf:"bytes,1,opt,name=trackId,proto3" json:"trackId,omitempty"`
	Status  Status                     `protobuf:"varint,2,opt,name=status,proto3,enum=graphqleditor.messages.Status" json:"status,omitempty"`
	Errors  []*LogStreamResponse_Error `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
}

func (x *LogStreamResponse) Reset() {
	*x = LogStreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphql_editor_messages_messages_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogStreamResponse) ProtoMessage() {}

func (x *LogStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graphql_editor_messages_messages_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogStreamResponse.ProtoReflect.Descriptor instead.
func (*LogStreamResponse) Descriptor() ([]byte, []int) {
	return file_graphql_editor_messages_messages_proto_rawDescGZIP(), []int{10}
}

func (x *LogStreamResponse) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

func (x *LogStreamResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OK
}

func (x *LogStreamResponse) GetErrors() []*LogStreamResponse_Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

type TextStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrackId string `protobuf:"bytes,1,opt,name=trackId,proto3" json:"trackId,omitempty"`
}

func (x *TextStreamRequest) Reset() {
	*x = TextStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphql_editor_messages_messages_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextStreamRequest) ProtoMessage() {}

func (x *TextStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graphql_editor_messages_messages_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextStreamRequest.ProtoReflect.Descriptor instead.
func (*TextStreamRequest) Descriptor() ([]byte, []int) {
	return file_graphql_editor_messages_messages_proto_rawDescGZIP(), []int{11}
}

func (x *TextStreamRequest) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

type TextStreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status Status                      `protobuf:"varint,1,opt,name=status,proto3,enum=graphqleditor.messages.Status" json:"status,omitempty"`
	Lines  []string                    `protobuf:"bytes,2,rep,name=lines,proto3" json:"lines,omitempty"`
	Errors []*TextStreamResponse_Error `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
}

func (x *TextStreamResponse) Reset() {
	*x = TextStreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphql_editor_messages_messages_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextStreamResponse) ProtoMessage() {}

func (x *TextStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graphql_editor_messages_messages_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextStreamResponse.ProtoReflect.Descriptor instead.
func (*TextStreamResponse) Descriptor() ([]byte, []int) {
	return file_graphql_editor_messages_messages_proto_rawDescGZIP(), []int{12}
}

func (x *TextStreamResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OK
}

func (x *TextStreamResponse) GetLines() []string {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *TextStreamResponse) GetErrors() []*TextStreamResponse_Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

type SubscriptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
}

func (x *SubscriptionRequest) Reset() {
	*x = SubscriptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphql_editor_messages_messages_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionRequest) ProtoMessage() {}

func (x *SubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graphql_editor_messages_messages_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionRequest.ProtoReflect.Descriptor instead.
func (*SubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_graphql_editor_messages_messages_proto_rawDescGZIP(), []int{13}
}

func (x *SubscriptionRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type SubscrptionPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data   *messages.Value   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Errors []*messages.Value `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
}

func (x *SubscrptionPayload) Reset() {
	*x = SubscrptionPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphql_editor_messages_messages_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscrptionPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscrptionPayload) ProtoMessage() {}

func (x *SubscrptionPayload) ProtoReflect() protoreflect.Message {
	mi := &file_graphql_editor_messages_messages_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscrptionPayload.ProtoReflect.Descriptor instead.
func (*SubscrptionPayload) Descriptor() ([]byte, []int) {
	return file_graphql_editor_messages_messages_proto_rawDescGZIP(), []int{14}
}

func (x *SubscrptionPayload) GetData() *messages.Value {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SubscrptionPayload) GetErrors() []*messages.Value {
	if x != nil {
		return x.Errors
	}
	return nil
}

type SubscriptionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload *SubscrptionPayload           `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Errors  []*SubscriptionResponse_Error `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
}

func (x *SubscriptionResponse) Reset() {
	*x = SubscriptionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphql_editor_messages_messages_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionResponse) ProtoMessage() {}

func (x *SubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graphql_editor_messages_messages_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionResponse.ProtoReflect.Descriptor instead.
func (*SubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_graphql_editor_messages_messages_proto_rawDescGZIP(), []int{15}
}

func (x *SubscriptionResponse) GetPayload() *SubscrptionPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SubscriptionResponse) GetErrors() []*SubscriptionResponse_Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

type CreateFunctionResponse_Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind CreateFunctionResponse_Error_ErrorKind `protobuf:"varint,1,opt,name=kind,proto3,enum=graphqleditor.messages.CreateFunctionResponse_Error_ErrorKind" json:"kind,omitempty"`
	Msg  string                                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *CreateFunctionResponse_Error) Reset() {
	*x = CreateFunctionResponse_Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphql_editor_messages_messages_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFunctionResponse_Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFunctionResponse_Error) ProtoMessage() {}

func (x *CreateFunctionResponse_Error) ProtoReflect() protoreflect.Message {
	mi := &file_graphql_editor_messages_messages_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFunctionResponse_Error.ProtoReflect.Descriptor instead.
func (*CreateFunctionResponse_Error) Descriptor() ([]byte, []int) {
	return file_graphql_editor_messages_messages_proto_rawDescGZIP(), []int{2, 0}
}

func (x *CreateFunctionResponse_Error) GetKind() CreateFunctionResponse_Error_ErrorKind {
	if x != nil {
		return x.Kind
	}
	return CreateFunctionResponse_Error_UNKNOWN
}

func (x *CreateFunctionResponse_Error) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type UpdateFunctionResponse_Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind UpdateFunctionResponse_Error_ErrorKind `protobuf:"varint,1,opt,name=kind,proto3,enum=graphqleditor.messages.UpdateFunctionResponse_Error_ErrorKind" json:"kind,omitempty"`
	Msg  string                                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *UpdateFunctionResponse_Error) Reset() {
	*x = UpdateFunctionResponse_Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphql_editor_messages_messages_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFunctionResponse_Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFunctionResponse_Error) ProtoMessage() {}

func (x *UpdateFunctionResponse_Error) ProtoReflect() protoreflect.Message {
	mi := &file_graphql_editor_messages_messages_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFunctionResponse_Error.ProtoReflect.Descriptor instead.
func (*UpdateFunctionResponse_Error) Descriptor() ([]byte, []int) {
	return file_graphql_editor_messages_messages_proto_rawDescGZIP(), []int{6, 0}
}

func (x *UpdateFunctionResponse_Error) GetKind() UpdateFunctionResponse_Error_ErrorKind {
	if x != nil {
		return x.Kind
	}
	return UpdateFunctionResponse_Error_UNKNOWN
}

func (x *UpdateFunctionResponse_Error) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type DeleteFunctionResponse_Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind DeleteFunctionResponse_Error_ErrorKind `protobuf:"varint,1,opt,name=kind,proto3,enum=graphqleditor.messages.DeleteFunctionResponse_Error_ErrorKind" json:"kind,omitempty"`
	Msg  string                                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *DeleteFunctionResponse_Error) Reset() {
	*x = DeleteFunctionResponse_Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphql_editor_messages_messages_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFunctionResponse_Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFunctionResponse_Error) ProtoMessage() {}

func (x *DeleteFunctionResponse_Error) ProtoReflect() protoreflect.Message {
	mi := &file_graphql_editor_messages_messages_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFunctionResponse_Error.ProtoReflect.Descriptor instead.
func (*DeleteFunctionResponse_Error) Descriptor() ([]byte, []int) {
	return file_graphql_editor_messages_messages_proto_rawDescGZIP(), []int{8, 0}
}

func (x *DeleteFunctionResponse_Error) GetKind() DeleteFunctionResponse_Error_ErrorKind {
	if x != nil {
		return x.Kind
	}
	return DeleteFunctionResponse_Error_UNKNOWN
}

func (x *DeleteFunctionResponse_Error) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type LogStreamResponse_Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind LogStreamResponse_Error_ErrorKind `protobuf:"varint,1,opt,name=kind,proto3,enum=graphqleditor.messages.LogStreamResponse_Error_ErrorKind" json:"kind,omitempty"`
	Msg  string                            `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *LogStreamResponse_Error) Reset() {
	*x = LogStreamResponse_Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphql_editor_messages_messages_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogStreamResponse_Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogStreamResponse_Error) ProtoMessage() {}

func (x *LogStreamResponse_Error) ProtoReflect() protoreflect.Message {
	mi := &file_graphql_editor_messages_messages_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogStreamResponse_Error.ProtoReflect.Descriptor instead.
func (*LogStreamResponse_Error) Descriptor() ([]byte, []int) {
	return file_graphql_editor_messages_messages_proto_rawDescGZIP(), []int{10, 0}
}

func (x *LogStreamResponse_Error) GetKind() LogStreamResponse_Error_ErrorKind {
	if x != nil {
		return x.Kind
	}
	return LogStreamResponse_Error_UNKNOWN
}

func (x *LogStreamResponse_Error) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type TextStreamResponse_Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind TextStreamResponse_Error_ErrorKind `protobuf:"varint,1,opt,name=kind,proto3,enum=graphqleditor.messages.TextStreamResponse_Error_ErrorKind" json:"kind,omitempty"`
	Msg  string                             `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *TextStreamResponse_Error) Reset() {
	*x = TextStreamResponse_Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphql_editor_messages_messages_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextStreamResponse_Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextStreamResponse_Error) ProtoMessage() {}

func (x *TextStreamResponse_Error) ProtoReflect() protoreflect.Message {
	mi := &file_graphql_editor_messages_messages_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextStreamResponse_Error.ProtoReflect.Descriptor instead.
func (*TextStreamResponse_Error) Descriptor() ([]byte, []int) {
	return file_graphql_editor_messages_messages_proto_rawDescGZIP(), []int{12, 0}
}

func (x *TextStreamResponse_Error) GetKind() TextStreamResponse_Error_ErrorKind {
	if x != nil {
		return x.Kind
	}
	return TextStreamResponse_Error_UNKNOWN
}

func (x *TextStreamResponse_Error) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type SubscriptionResponse_Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind SubscriptionResponse_Error_ErrorKind `protobuf:"varint,1,opt,name=kind,proto3,enum=graphqleditor.messages.SubscriptionResponse_Error_ErrorKind" json:"kind,omitempty"`
	Msg  string                               `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *SubscriptionResponse_Error) Reset() {
	*x = SubscriptionResponse_Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphql_editor_messages_messages_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscriptionResponse_Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionResponse_Error) ProtoMessage() {}

func (x *SubscriptionResponse_Error) ProtoReflect() protoreflect.Message {
	mi := &file_graphql_editor_messages_messages_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionResponse_Error.ProtoReflect.Descriptor instead.
func (*SubscriptionResponse_Error) Descriptor() ([]byte, []int) {
	return file_graphql_editor_messages_messages_proto_rawDescGZIP(), []int{15, 0}
}

func (x *SubscriptionResponse_Error) GetKind() SubscriptionResponse_Error_ErrorKind {
	if x != nil {
		return x.Kind
	}
	return SubscriptionResponse_Error_UNKNOWN
}

func (x *SubscriptionResponse_Error) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_graphql_editor_messages_messages_proto protoreflect.FileDescriptor

var file_graphql_editor_messages_messages_proto_rawDesc = []byte{
	0x0a, 0x26, 0x67, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x2d, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72,
	0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x67, 0x72, 0x61, 0x70, 0x68, 0x71,
	0x6c, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x1a, 0x31, 0x73, 0x74, 0x75, 0x63, 0x63, 0x6f, 0x2d, 0x74, 0x73, 0x2d, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2d, 0x67, 0x65, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xa0, 0x01, 0x0a, 0x08, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61,
	0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e,
	0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x77, 0x6f, 0x72, 0x6b,
	0x5f, 0x64, 0x69, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x77, 0x6f, 0x72, 0x6b,
	0x44, 0x69, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x75, 0x69,
	0x6c, 0x64, 0x5f, 0x63, 0x6d, 0x64, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x62, 0x75,
	0x69, 0x6c, 0x64, 0x43, 0x6d, 0x64, 0x22, 0x55, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x3c, 0x0a, 0x08, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x20, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x65, 0x64, 0x69, 0x74, 0x6f,
	0x72, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x46, 0x75, 0x6e, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x08, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xc2, 0x02,
	0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x72, 0x61, 0x63,
	0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x72, 0x61, 0x63, 0x6b,
	0x49, 0x64, 0x12, 0x36, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x65, 0x64, 0x69, 0x74,
	0x6f, 0x72, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x4c, 0x0a, 0x06, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x67, 0x72, 0x61,
	0x70, 0x68, 0x71, 0x6c, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x1a, 0x87, 0x01, 0x0a, 0x05, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x12, 0x52, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x3e, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72,
	0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4b, 0x69, 0x6e, 0x64,
	0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x18, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e,
	0x10, 0x00, 0x22, 0x53, 0x0a, 0x13, 0x52, 0x65, 0x61, 0x64, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3c, 0x0a, 0x08, 0x66, 0x75, 0x6e,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x67, 0x72,
	0x61, 0x70, 0x68, 0x71, 0x6c, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x2e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x66,
	0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x6c, 0x0a, 0x14, 0x52, 0x65, 0x61, 0x64, 0x46,
	0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x42, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x2a, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x2e,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x46, 0x75, 0x6e,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x55, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46,
	0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3c,
	0x0a, 0x08, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72,
	0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x08, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xc2, 0x02, 0x0a,
	0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x72, 0x61, 0x63, 0x6b,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x49,
	0x64, 0x12, 0x36, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1e, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x65, 0x64, 0x69, 0x74, 0x6f,
	0x72, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x4c, 0x0a, 0x06, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x67, 0x72, 0x61, 0x70,
	0x68, 0x71, 0x6c, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52,
	0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x1a, 0x87, 0x01, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x52, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x3e, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x2e,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46,
	0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4b, 0x69, 0x6e, 0x64, 0x52,
	0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x18, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x4b, 0x69, 0x6e, 0x64, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10,
	0x00, 0x22, 0x55, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x75, 0x6e, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3c, 0x0a, 0x08, 0x66, 0x75,
	0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x67,
	0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08,
	0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xc2, 0x02, 0x0a, 0x16, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x49, 0x64, 0x12, 0x36, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e,
	0x67, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x4c, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x65,
	0x64, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x06, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x73, 0x1a, 0x87, 0x01, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x52, 0x0a,
	0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x3e, 0x2e, 0x67, 0x72,
	0x61, 0x70, 0x68, 0x71, 0x6c, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x75, 0x6e, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e,
	0x64, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6d, 0x73, 0x67, 0x22, 0x18, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4b, 0x69, 0x6e, 0x64,
	0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x22, 0x50, 0x0a,
	0x10, 0x4c, 0x6f, 0x67, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x3c, 0x0a, 0x08, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x65, 0x64, 0x69,
	0x74, 0x6f, 0x72, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x46, 0x75, 0x6e,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0xb3, 0x02, 0x0a, 0x11, 0x4c, 0x6f, 0x67, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x49, 0x64, 0x12,
	0x36, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x1e, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x2e,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x47, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x71,
	0x6c, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x2e, 0x4c, 0x6f, 0x67, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73,
	0x1a, 0x82, 0x01, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x4d, 0x0a, 0x04, 0x6b, 0x69,
	0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x39, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68,
	0x71, 0x6c, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x2e, 0x4c, 0x6f, 0x67, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4b,
	0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x18, 0x0a, 0x09, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e,
	0x4f, 0x57, 0x4e, 0x10, 0x00, 0x22, 0x2d, 0x0a, 0x11, 0x54, 0x65, 0x78, 0x74, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x72,
	0x61, 0x63, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x72, 0x61,
	0x63, 0x6b, 0x49, 0x64, 0x22, 0xb2, 0x02, 0x0a, 0x12, 0x54, 0x65, 0x78, 0x74, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x67, 0x72,
	0x61, 0x70, 0x68, 0x71, 0x6c, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x05, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x12, 0x48, 0x0a, 0x06, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x67, 0x72, 0x61, 0x70,
	0x68, 0x71, 0x6c, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x06, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x73, 0x1a, 0x83, 0x01, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x4e, 0x0a,
	0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x3a, 0x2e, 0x67, 0x72,
	0x61, 0x70, 0x68, 0x71, 0x6c, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22,
	0x18, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x0b, 0x0a, 0x07,
	0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x22, 0x34, 0x0a, 0x13, 0x53, 0x75, 0x62,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x22,
	0x70, 0x0a, 0x12, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x74, 0x75, 0x63, 0x63, 0x6f, 0x2e, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x2e, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x73, 0x74, 0x75, 0x63, 0x63, 0x6f, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x73, 0x22, 0xb0, 0x02, 0x0a, 0x14, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x67, 0x72,
	0x61, 0x70, 0x68, 0x71, 0x6c, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x12, 0x4a, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x32, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72,
	0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x1a, 0x85, 0x01, 0x0a,
	0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x50, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x3c, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x65, 0x64,
	0x69, 0x74, 0x6f, 0x72, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x53, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4b, 0x69,
	0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x18, 0x0a, 0x09, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f,
	0x57, 0x4e, 0x10, 0x00, 0x2a, 0x17, 0x0a, 0x07, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x12,
	0x0c, 0x0a, 0x08, 0x4e, 0x4f, 0x44, 0x45, 0x4a, 0x53, 0x31, 0x34, 0x10, 0x00, 0x2a, 0x1b, 0x0a,
	0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12,
	0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x2a, 0x42, 0x0a, 0x12, 0x52, 0x65,
	0x61, 0x64, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x09, 0x0a, 0x05, 0x52, 0x45, 0x41, 0x44, 0x59, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x49,
	0x4e, 0x5f, 0x50, 0x52, 0x4f, 0x47, 0x52, 0x45, 0x53, 0x53, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c,
	0x4e, 0x4f, 0x54, 0x5f, 0x44, 0x45, 0x50, 0x4c, 0x4f, 0x59, 0x45, 0x44, 0x10, 0x02, 0x42, 0x4e,
	0x5a, 0x4c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x72, 0x61,
	0x70, 0x68, 0x71, 0x6c, 0x2d, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x2f, 0x67, 0x72, 0x61, 0x70,
	0x68, 0x71, 0x6c, 0x5f, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x2f, 0x67, 0x6f, 0x2f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x2d, 0x65,
	0x64, 0x69, 0x74, 0x6f, 0x72, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_graphql_editor_messages_messages_proto_rawDescOnce sync.Once
	file_graphql_editor_messages_messages_proto_rawDescData = file_graphql_editor_messages_messages_proto_rawDesc
)

func file_graphql_editor_messages_messages_proto_rawDescGZIP() []byte {
	file_graphql_editor_messages_messages_proto_rawDescOnce.Do(func() {
		file_graphql_editor_messages_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_graphql_editor_messages_messages_proto_rawDescData)
	})
	return file_graphql_editor_messages_messages_proto_rawDescData
}

var file_graphql_editor_messages_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 9)
var file_graphql_editor_messages_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_graphql_editor_messages_messages_proto_goTypes = []interface{}{
	(Runtime)(0),            // 0: graphqleditor.messages.Runtime
	(Status)(0),             // 1: graphqleditor.messages.Status
	(ReadFunctionStatus)(0), // 2: graphqleditor.messages.ReadFunctionStatus
	(CreateFunctionResponse_Error_ErrorKind)(0), // 3: graphqleditor.messages.CreateFunctionResponse.Error.ErrorKind
	(UpdateFunctionResponse_Error_ErrorKind)(0), // 4: graphqleditor.messages.UpdateFunctionResponse.Error.ErrorKind
	(DeleteFunctionResponse_Error_ErrorKind)(0), // 5: graphqleditor.messages.DeleteFunctionResponse.Error.ErrorKind
	(LogStreamResponse_Error_ErrorKind)(0),      // 6: graphqleditor.messages.LogStreamResponse.Error.ErrorKind
	(TextStreamResponse_Error_ErrorKind)(0),     // 7: graphqleditor.messages.TextStreamResponse.Error.ErrorKind
	(SubscriptionResponse_Error_ErrorKind)(0),   // 8: graphqleditor.messages.SubscriptionResponse.Error.ErrorKind
	(*Function)(nil),                     // 9: graphqleditor.messages.Function
	(*CreateFunctionRequest)(nil),        // 10: graphqleditor.messages.CreateFunctionRequest
	(*CreateFunctionResponse)(nil),       // 11: graphqleditor.messages.CreateFunctionResponse
	(*ReadFunctionRequest)(nil),          // 12: graphqleditor.messages.ReadFunctionRequest
	(*ReadFunctionResponse)(nil),         // 13: graphqleditor.messages.ReadFunctionResponse
	(*UpdateFunctionRequest)(nil),        // 14: graphqleditor.messages.UpdateFunctionRequest
	(*UpdateFunctionResponse)(nil),       // 15: graphqleditor.messages.UpdateFunctionResponse
	(*DeleteFunctionRequest)(nil),        // 16: graphqleditor.messages.DeleteFunctionRequest
	(*DeleteFunctionResponse)(nil),       // 17: graphqleditor.messages.DeleteFunctionResponse
	(*LogStreamRequest)(nil),             // 18: graphqleditor.messages.LogStreamRequest
	(*LogStreamResponse)(nil),            // 19: graphqleditor.messages.LogStreamResponse
	(*TextStreamRequest)(nil),            // 20: graphqleditor.messages.TextStreamRequest
	(*TextStreamResponse)(nil),           // 21: graphqleditor.messages.TextStreamResponse
	(*SubscriptionRequest)(nil),          // 22: graphqleditor.messages.SubscriptionRequest
	(*SubscrptionPayload)(nil),           // 23: graphqleditor.messages.SubscrptionPayload
	(*SubscriptionResponse)(nil),         // 24: graphqleditor.messages.SubscriptionResponse
	(*CreateFunctionResponse_Error)(nil), // 25: graphqleditor.messages.CreateFunctionResponse.Error
	(*UpdateFunctionResponse_Error)(nil), // 26: graphqleditor.messages.UpdateFunctionResponse.Error
	(*DeleteFunctionResponse_Error)(nil), // 27: graphqleditor.messages.DeleteFunctionResponse.Error
	(*LogStreamResponse_Error)(nil),      // 28: graphqleditor.messages.LogStreamResponse.Error
	(*TextStreamResponse_Error)(nil),     // 29: graphqleditor.messages.TextStreamResponse.Error
	(*SubscriptionResponse_Error)(nil),   // 30: graphqleditor.messages.SubscriptionResponse.Error
	(*messages.Value)(nil),               // 31: stucco.messages.Value
}
var file_graphql_editor_messages_messages_proto_depIdxs = []int32{
	9,  // 0: graphqleditor.messages.CreateFunctionRequest.function:type_name -> graphqleditor.messages.Function
	1,  // 1: graphqleditor.messages.CreateFunctionResponse.status:type_name -> graphqleditor.messages.Status
	25, // 2: graphqleditor.messages.CreateFunctionResponse.errors:type_name -> graphqleditor.messages.CreateFunctionResponse.Error
	9,  // 3: graphqleditor.messages.ReadFunctionRequest.function:type_name -> graphqleditor.messages.Function
	2,  // 4: graphqleditor.messages.ReadFunctionResponse.status:type_name -> graphqleditor.messages.ReadFunctionStatus
	9,  // 5: graphqleditor.messages.UpdateFunctionRequest.function:type_name -> graphqleditor.messages.Function
	1,  // 6: graphqleditor.messages.UpdateFunctionResponse.status:type_name -> graphqleditor.messages.Status
	26, // 7: graphqleditor.messages.UpdateFunctionResponse.errors:type_name -> graphqleditor.messages.UpdateFunctionResponse.Error
	9,  // 8: graphqleditor.messages.DeleteFunctionRequest.function:type_name -> graphqleditor.messages.Function
	1,  // 9: graphqleditor.messages.DeleteFunctionResponse.status:type_name -> graphqleditor.messages.Status
	27, // 10: graphqleditor.messages.DeleteFunctionResponse.errors:type_name -> graphqleditor.messages.DeleteFunctionResponse.Error
	9,  // 11: graphqleditor.messages.LogStreamRequest.function:type_name -> graphqleditor.messages.Function
	1,  // 12: graphqleditor.messages.LogStreamResponse.status:type_name -> graphqleditor.messages.Status
	28, // 13: graphqleditor.messages.LogStreamResponse.errors:type_name -> graphqleditor.messages.LogStreamResponse.Error
	1,  // 14: graphqleditor.messages.TextStreamResponse.status:type_name -> graphqleditor.messages.Status
	29, // 15: graphqleditor.messages.TextStreamResponse.errors:type_name -> graphqleditor.messages.TextStreamResponse.Error
	31, // 16: graphqleditor.messages.SubscrptionPayload.data:type_name -> stucco.messages.Value
	31, // 17: graphqleditor.messages.SubscrptionPayload.errors:type_name -> stucco.messages.Value
	23, // 18: graphqleditor.messages.SubscriptionResponse.payload:type_name -> graphqleditor.messages.SubscrptionPayload
	30, // 19: graphqleditor.messages.SubscriptionResponse.errors:type_name -> graphqleditor.messages.SubscriptionResponse.Error
	3,  // 20: graphqleditor.messages.CreateFunctionResponse.Error.kind:type_name -> graphqleditor.messages.CreateFunctionResponse.Error.ErrorKind
	4,  // 21: graphqleditor.messages.UpdateFunctionResponse.Error.kind:type_name -> graphqleditor.messages.UpdateFunctionResponse.Error.ErrorKind
	5,  // 22: graphqleditor.messages.DeleteFunctionResponse.Error.kind:type_name -> graphqleditor.messages.DeleteFunctionResponse.Error.ErrorKind
	6,  // 23: graphqleditor.messages.LogStreamResponse.Error.kind:type_name -> graphqleditor.messages.LogStreamResponse.Error.ErrorKind
	7,  // 24: graphqleditor.messages.TextStreamResponse.Error.kind:type_name -> graphqleditor.messages.TextStreamResponse.Error.ErrorKind
	8,  // 25: graphqleditor.messages.SubscriptionResponse.Error.kind:type_name -> graphqleditor.messages.SubscriptionResponse.Error.ErrorKind
	26, // [26:26] is the sub-list for method output_type
	26, // [26:26] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_graphql_editor_messages_messages_proto_init() }
func file_graphql_editor_messages_messages_proto_init() {
	if File_graphql_editor_messages_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_graphql_editor_messages_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Function); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphql_editor_messages_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFunctionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphql_editor_messages_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFunctionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphql_editor_messages_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadFunctionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphql_editor_messages_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadFunctionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphql_editor_messages_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateFunctionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphql_editor_messages_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateFunctionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphql_editor_messages_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFunctionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphql_editor_messages_messages_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFunctionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphql_editor_messages_messages_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphql_editor_messages_messages_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogStreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphql_editor_messages_messages_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphql_editor_messages_messages_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextStreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphql_editor_messages_messages_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscriptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphql_editor_messages_messages_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscrptionPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphql_editor_messages_messages_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscriptionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphql_editor_messages_messages_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFunctionResponse_Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphql_editor_messages_messages_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateFunctionResponse_Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphql_editor_messages_messages_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFunctionResponse_Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphql_editor_messages_messages_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogStreamResponse_Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphql_editor_messages_messages_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextStreamResponse_Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphql_editor_messages_messages_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscriptionResponse_Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_graphql_editor_messages_messages_proto_rawDesc,
			NumEnums:      9,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_graphql_editor_messages_messages_proto_goTypes,
		DependencyIndexes: file_graphql_editor_messages_messages_proto_depIdxs,
		EnumInfos:         file_graphql_editor_messages_messages_proto_enumTypes,
		MessageInfos:      file_graphql_editor_messages_messages_proto_msgTypes,
	}.Build()
	File_graphql_editor_messages_messages_proto = out.File
	file_graphql_editor_messages_messages_proto_rawDesc = nil
	file_graphql_editor_messages_messages_proto_goTypes = nil
	file_graphql_editor_messages_messages_proto_depIdxs = nil
}
